### ISSUE TITLE
一直检测不到图像

### ISSUE THREAD

**Issue by zzp198** [shiokaze/UmamusumeAutoTrainer#10]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/1561e77e-e4ef-4f49-89bc-f65df4cfda17)

**Comment by shiokaze** [comment]
用任务管理器关闭adb.exe后重试下

**Comment by zzp198** [comment]
全部杀了重新开还是一样，不知道是哪里出了问题，mumu12的配置还有其他要求吗

**Comment by shiokaze** [comment]
检查一下端口是否正确，可以提供一下任务启动时连接模拟器的日志

**Comment by zzp198** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/6c93fdfa-2442-47a8-b309-c9e8cd88fe96)

**Comment by shiokaze** [comment]
不太清楚，我用的模拟器版本是3.5.5.1877，没出现过图传失败的问题。设置除了分辨率以外其他都是默认的，如果重启电脑也不行的话就重装下模拟器吧

**Comment by PSGXYS** [comment]
模拟器上有个ATX应用，可能是ATX服务没有启动

**Comment by PSGXYS** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/44258992/c6e34b43-70b5-4039-92bd-f281bc378107)
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/44258992/bb8449c6-413a-4d21-a085-63c994d79ed9)

**Comment by zzp198** [comment]
我这没有ATX,是adb自动安装还是手动?

**Comment by zzp198** [comment]
我用python -m uiautomator init手动安装atx-agent后,错误还是有
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/fd3a7077-b98e-43ae-be04-3648cfe860f1)
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/bdd2a27d-60dd-4cbc-ab3c-6fbf0999899d)

**Comment by PSGXYS** [comment]
这个log应该是能识别到了，你进游戏主页试试

**Comment by zzp198** [comment]
一样，错误提示其实还是英文版的找不到UI,图片右上角有点击的标识
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/154792ea-ab7a-4987-8da3-64bd50717a7b)

**Comment by shiokaze** [comment]
有一个正在进行的育成，手动进入之后就行了

**Comment by zzp198** [comment]
不行啊，还是找不到UI，一直点击右上角
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/724ba494-3a2b-4449-b55f-f12c48762ba1)

**Comment by shiokaze** [comment]
720*1280分辨率对吗，如果没错的话只能在代码里cv2.imshow打印一下实际收取到的图片定位问题了

**Comment by zzp198** [comment]
我把截的图保存下来了，但是全都是模拟器主界面的图，发现问题了，是我开着“后台挂机时保活运行”的问题，这个时候app都是独立的，截取不到当前游戏界面而是atx的模拟器主界面.
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/f6ff3c79-3a3e-45ab-b50e-3898cd7b8a66)
![debug - 副本](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/a57db79d-4189-437b-8752-1bad2196dda5)
这个就是开启“保活运行”截的图，当时界面是游戏界面截的确是模拟器主界面。
![img](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/2ea0f335-7c3f-41cf-bb1b-bea79762e875)
这个是关闭后的，模拟器显示啥截的就是啥

**Comment by zzp198** [comment]
可以正常使用了，readme里面最好添一下“记得关闭后台保活”
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/129676925/d6413c2f-af2c-42c1-ae2d-f453134ad6ee)

**Comment by shiokaze** [comment]
ok
