### ISSUE TITLE
运行育成任务提示系统异常

### ISSUE THREAD

**Issue by justcoko** [shiokaze/UmamusumeAutoTrainer#100]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/147731524/f00e5f58-df0f-49f5-a3e0-8ee084386cb4)

**Comment by shiokaze** [comment]
https://blog.csdn.net/liguilicsdn/article/details/50902194
参考下这个看下能否解决

**Comment by justcoko** [comment]
解决了
