### ISSUE TITLE
报错 NOT-FOUND-UI

### ISSUE THREAD

**Issue by 1125197567** [shiokaze/UmamusumeAutoTrainer#105]
![报错](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/60338938/937ea70c-0c3f-4150-979a-eb72b835d9f7)

**Comment by zylbmrx** [comment]
看看横竖屏和分辨率

**Comment by 1125197567** [comment]
> 看看横竖屏和分辨率
=这个都没问题，后面我重启解决了
