### ISSUE TITLE
系统异常： TypeError: '>' not supported between instances of 'int' and 'str' 

### ISSUE THREAD

**Issue by DYDY233** [shiokaze/UmamusumeAutoTrainer#108]
安装完依赖成功打开UAT，设置完目标后开始任务，报系统异常
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/45912021/d442ab65-ca47-4f1a-a68f-16bfb585b587)

**Comment by DYDY233** [comment]
需要去对应的cultivate.py的42行加一下类型转换

**Comment by shiokaze** [comment]
应该是你启动的时候把，“超过此pt后学习技能”里面的数字填成了空？

**Comment by DYDY233** [comment]
> 应该是你启动的时候把，“超过此pt后学习技能”里面的数字填成了空？

不是，我填的9999

**Comment by DYDY233** [comment]
> 应该是你启动的时候把，“超过此pt后学习技能”里面的数字填成了空？

我回去看了看了下保存的记录，确实是没有填。应该是因为这个，解决啦，Thanks♪(･ω･)ﾉ
