### ISSUE TITLE
点击训练后提示not found UI

### ISSUE THREAD

**Issue by 101142TS** [shiokaze/UmamusumeAutoTrainer#109]
点击训练后能正常进入训练界面，而后就一直提示NOT_FOUND_UI

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/16666362/382105ba-abe5-42fd-90a8-ef2c9ce393fe)

**Comment by shiokaze** [comment]
把上面显示坐标的功能关掉再试试

**Comment by 101142TS** [comment]
确实是这个问题
