### ISSUE TITLE
此项目被人用于盈利了

### ISSUE THREAD

**Issue by centuoho** [shiokaze/UmamusumeAutoTrainer#124]
![Screenshot_2023-12-15-08-13-25-566_tv danmaku bili](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/126691528/0016d2b6-5919-406d-a718-25f66e86e51d)
![Screenshot_2023-12-15-08-13-11-421_com tencent mobileqq](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/126691528/838d582d-3906-409b-afcd-a9f7e79052f8)
![Screenshot_2023-12-15-08-13-09-709_com tencent mobileqq](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/126691528/94bdcad5-4e82-4adb-8b43-f81c2d994440)

**Comment by centuoho** [comment]
视频链接【赛马娘自动，利用python养马-哔哩哔哩】 https://b23.tv/JYN7dPZ

**Comment by shiokaze** [comment]
没关系，开源了也避免不了这些
