### ISSUE TITLE
请问如何添加新的支援卡？

### ISSUE THREAD

**Issue by timeance** [shiokaze/UmamusumeAutoTrainer#137]
想借活动卡刷pt；尝试直接修改 userdate 添加新卡的名称后，应用预设时网页会卡死，控制台无报错

**Comment by shiokaze** [comment]
在https://github.com/shiokaze/UmamusumeAutoTrainer/blob/dev/web/src/components/TaskEditModal.vue#L430
添加支援卡后使用npm重新构建前端文件即可
