### ISSUE TITLE
希望增加不使用闹钟功能

### ISSUE THREAD

**Issue by toloomis** [shiokaze/UmamusumeAutoTrainer#14]
目前开服支援卡不齐全，育成容易失败，很多时候都是浪费闹钟，希望能增加一个闹钟开关功能

因为北黑前我只想凑一下600属性，然后刷一下三星蓝因子

**Comment by PSGXYS** [comment]
其实可以这样，自己设置每次比赛失败后最多使用几个闹钟，设置0就是不使用
