### ISSUE TITLE
powershell已经调至管理员模式，打开install.ps1后立即闪退没有信息提示（有一次有短暂的红色字体），没有出现venv文件夹

### ISSUE THREAD

**Issue by DDKing-ZJU** [shiokaze/UmamusumeAutoTrainer#17]
python版本 使用 python --version 检测出为3.10.9，本地有其他版本的python
run.ps1也是打开即闪退
win11系统

**Comment by shiokaze** [comment]
可以先打开终端用命令行方式启动，这样就不会因为闪退导致看不到报错原因了

**Comment by DDKing-ZJU** [comment]
在cmd里面输入了 powershell.exe -file install.ps1之后发现出现了“在此系统上禁止运行脚本”的字样
问题已经解决。
解决方案如下
1.首先用管理员模式打开powershell
2.输入set-ExecutionPolicy RemoteSigned命令
3.出现“[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“N”):”字样，输入Y后回车
4.重新运行脚本

**Comment by shiokaze** [comment]
ok，稍后记录到readme
