### ISSUE TITLE
系统的用户名不能为中文

### ISSUE THREAD

**Issue by DDKing-ZJU** [shiokaze/UmamusumeAutoTrainer#18]
系统用户名为中文会导致python依赖安装的文件夹包含中文导致运行错误。
解决方式：https://zhuanlan.zhihu.com/p/440768641

**Comment by Zayn3** [comment]
修改Windows的用户文件夹操作繁琐还有风险, 本人是把该文件夹复制到其他盘里面,
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/48514715/856cc478-fea0-4c37-8487-b296f4a32a27)
然后修改paddleocr.py, network.py这两个文件的路径
