### ISSUE TITLE
没法正常启动

### ISSUE THREAD

**Issue by wlsm0** [shiokaze/UmamusumeAutoTrainer#24]
截了几次屏才截到

![0011](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144103843/889450ed-51a1-4c9f-b29b-44d9bc540d9b)

**Comment by shiokaze** [comment]
路径不要带中文

**Comment by shiokaze** [comment]
参考 https://github.com/shiokaze/UmamusumeAutoTrainer/issues/18

**Comment by wlsm0** [comment]
谢谢，解决了
