### ISSUE TITLE
脚本启动后浏览器打开url为全空，控制台报错

### ISSUE THREAD

**Issue by mooganic** [shiokaze/UmamusumeAutoTrainer#25]
打开浏览器输入http://127.0.0.1:8071/ 看到面板ui没有显示，内容全空

打开console，刷新网页看见error信息：
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by shiokaze** [comment]
参考https://github.com/shiokaze/UmamusumeAutoTrainer/issues/9

**Comment by mooganic** [comment]
HKEY_CLASSES_ROOT 下.js没有mimetypes值，不知道怎么新增

**Comment by mooganic** [comment]
尝试了把Content Type的值改为了text/javascript，webui正常显示

**Comment by shiokaze** [comment]
ok
