### ISSUE TITLE
更新活动信息处理后发现几个问题

### ISSUE THREAD

**Issue by Wsnoy** [shiokaze/UmamusumeAutoTrainer#26]
1. 刚开始养成时的因子继承界面不会自动选择2档跳过。
2.
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/d9ae4487-ebea-4c54-b400-86dfef9a8718)
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/775ddce9-abb7-467e-9809-4ce9f36227b6)

3. 
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/90defb99-6d76-4459-a972-22fd1756f843)
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/48418c61-f79b-40f5-9f36-44b055fe83b6)
2和3处出现未知的选项框。

4. 好像是识别不到UI，会卡在参赛处
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/ff9584fc-ef2b-4c72-84c6-b0e3c0a90271)
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/ec03ebbc-a7ec-4378-bc32-0d883c46b2b1)
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/e2606ecd-493a-436e-b90c-5279b0c9952d)

5. 学习技能时也会出现UI识别问题，卡住不动
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/cbd1db1d-af23-4c5b-a1eb-4780b6593047)
![图片](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/75603670/4dacb8d8-f1fb-4426-9ee2-11574e88fdc0)

（顺便问一下开局训练时心情是普通，但是耐力训练有4个协助卡人头，策略直接选择去外出了是否有点亏x）

**Comment by shiokaze** [comment]
可以git checkout先回滚到之前的提交看下是否有类似问题

**Comment by Wsnoy** [comment]
找到原因了，我这里是游戏里画质不能设置成简易版，设置成简易版就有以上问题。我寻思电脑太老了就都开低点儿，没想到会发生这种事（x），感谢
