### ISSUE TITLE
可能是数据结构判断的bug

### ISSUE THREAD

**Issue by DaNiuBigbull** [shiokaze/UmamusumeAutoTrainer#28]
![NEUN526Q4JS1I3H$5FZY@UO](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/108382387/384d79fa-01a9-46ea-8c60-ec0156457f42)
![DEXQP{PO9KCF(Y}( DQ_28T](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/108382387/34981088-1a5a-45cd-87e6-8bf94b7acdba)

**Comment by shiokaze** [comment]
<img width="283" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/17895801/f0dd832a-9e04-4fa4-9f43-1b9d2edad39b">
这里识别出错了，之后对这种异常情况增加一些兜底逻辑
