### ISSUE TITLE
启动时提示我缺少paddleocr

### ISSUE THREAD

**Issue by tlatixat** [shiokaze/UmamusumeAutoTrainer#3]
ModuleNotFoundError: No module named 'paddleocr'
这个orc识别我尝试安装一直装不上,没办法按照他们的提示pip,请问有什么办法能解决吗?

**Comment by shiokaze** [comment]
检查python版本是否为3.10.9，可以在命令行中输入python查看。

**Comment by shiokaze** [comment]
如果不知道怎么安装依赖的话，也可以用release里面已经处理好的版本

**Comment by tlatixat** [comment]
当然是3.10.9,我在他们的git库操作手册上执行到pip install "paddleocr>=2.0.1"结果失败,说找不到.然后我去pypl上直接找whl装就提示我各种各样的缺文件.
然后我使用的就是老兄你处理好的版本,但好像它不走一键包而是继续走我自己的依赖.

**Comment by tlatixat** [comment]
是的,用那个启动后窗口到报错阶段就直接自动关闭了.

**Comment by shiokaze** [comment]
用cmd在项目目录下面手动执行.\venv\Scripts\activate
如果命令行左边出现了(venv)，在执行python main.py

**Comment by shiokaze** [comment]
如果还是显示缺少依赖的话发送一下pip list的结果

**Comment by tlatixat** [comment]
E:\UmamusumeAutoTrainer>.\venv\Scripts\activate

(venv) E:\UmamusumeAutoTrainer>python main.py
Traceback (most recent call last):
  File "E:\UmamusumeAutoTrainer\main.py", line 5, in <module>
    from module.umamusume.manifest import UmamusumeManifest
  File "E:\UmamusumeAutoTrainer\module\umamusume\manifest.py", line 8, in <module>
    from module.umamusume.script.cultivate_task.cultivate import *
  File "E:\UmamusumeAutoTrainer\module\umamusume\script\cultivate_task\cultivate.py", line 8, in <module>
    from module.umamusume.script.cultivate_task.parse import *
  File "E:\UmamusumeAutoTrainer\module\umamusume\script\cultivate_task\parse.py", line 8, in <module>
    from bot.recog.ocr import ocr_line, find_similar_text
  File "E:\UmamusumeAutoTrainer\bot\recog\ocr.py", line 1, in <module>
    import paddleocr
ModuleNotFoundError: No module named 'paddleocr'

可惜,还是失败的

**Comment by tlatixat** [comment]
ERROR: Could not find a version that satisfies the requirement paddleocr>=2.0.1 (from versions: none)
ERROR: No matching distribution found for paddleocr>=2.0.1
pip的时候一直提示我找不到它,很奇怪

**Comment by shiokaze** [comment]
看一下pip list的结果？

**Comment by tlatixat** [comment]
(venv) E:\UmamusumeAutoTrainer>pip list
Package               Version
--------------------- -------------
addict                2.4.0
anyio                 4.0.0
astor                 0.8.1
certifi               2022.12.7
charset-normalizer    3.0.1
click                 8.1.3
colorama              0.4.6
colorlog              6.7.0
croniter              1.4.1
decorator             5.1.1
exceptiongroup        1.1.3
h11                   0.14.0
httpcore              0.17.3
httpx                 0.24.1
idna                  3.4
lion-pytorch          0.0.7
Markdown              3.4.1
markdown-it-py        2.2.0
mdurl                 0.1.2
mmcv-full             1.7.0
model-index           0.1.11
numpy                 1.24.2
opencv-contrib-python 4.8.0.76
opencv-python         4.5.5
openmim               0.3.6
opt-einsum            3.3.0
ordered-set           4.1.0
packaging             23.0
paddle-bfloat         0.1.7
paddlepaddle-gpu      2.5.1.post120
pandas                1.5.3
Pillow                9.4.0
pip                   23.0.1
plyer                 2.1.0
protobuf              3.20.2
psutil                5.9.5
Pygments              2.14.0
python-dateutil       2.8.2
pytz                  2022.7.1
PyYAML                6.0
regex                 2022.10.31
requests              2.28.2
rich                  13.3.1
scipy                 1.11.2
setuptools            65.5.0
Shapely               1.8.2
six                   1.16.0
sniffio               1.3.0
tabulate              0.9.0
tifffile              2023.8.30
torch                 1.13.1
typing_extensions     4.5.0
urllib3               1.26.14
yapf                  0.32.0

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) E:\UmamusumeAutoTrainer>

**Comment by jkf123cn** [comment]
(venv) PS D:\UmamusumeAutoTrainer> D:\UmamusumeAutoTrainer\run.ps1
python : No Python at '"C:\Users\22403\AppData\Local\Programs\Python\Python310\python.exe'
所在位置 D:\UmamusumeAutoTrainer\run.ps1:2 字符: 1
+ python main.py
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No Python at '"...310\python.exe':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
这是为啥

**Comment by shiokaze** [comment]
上传了新的安装方式，你这个可能是没有安装python

**Comment by jkf123cn** [comment]
.\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 D:\下载\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
这又为啥

**Comment by shiokaze** [comment]
> .\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名 称的拼写，如果包括路径，请确保路径正确，然后再试一次。 所在位置 D:\下载\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
> 
> * .\venv\Scripts\activate
> * ```
>     + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> 这又为啥

删除venv文件夹后重试

**Comment by jkf123cn** [comment]
creating venv...
.\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 D:\下载\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

activate venv failed
install failed
重新解压后打开也是这样

**Comment by shiokaze** [comment]
> creating venv... .\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名 称的拼写，如果包括路径，请确保路径正确，然后再试一次。 所在位置 D:\下载\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
> 
> * .\venv\Scripts\activate
> * ```
>     + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> activate venv failed install failed 重新解压后打开也是这样

python安装了吗，是否设置了正确的PATH？可以试一下在cmd内执行 python -m venv venv 是否能正常生成一个venv文件夹，且里面有venv\Scripts\activate文件

**Comment by shiokaze** [comment]
> creating venv... .\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名 称的拼写，如果包括路径，请确保路径正确，然后再试一次。 所在位置 D:\下载\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
> 
> * .\venv\Scripts\activate
> * ```
>     + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> activate venv failed install failed 重新解压后打开也是这样

另外，路径最好不要包含中文

**Comment by jkf123cn** [comment]
creating venv...
.\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 D:\UmamusumeAutoTrainer-main\install.ps1:29 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

activate venv failed
install failed

装了 能生成venv文件夹 路径没中文

**Comment by tlatixat** [comment]
> 上传了新的安装方式，你这个可能是没有安装python

老兄新的安装方式没问题,已经可以正常使用了,大晚上排bug辛苦了.
只是目前用米浴测试自定义赛程,找不到第一年3月后半的春季锦标赛和第三年三月下半的日经奖

**Comment by jkf123cn** [comment]
里面也有activate

**Comment by shiokaze** [comment]
> 

还是不行的话就直接执行pip install pyelftools==0.29 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pdf2docx==0.5.6 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install --upgrade -r requirements.txt -i https://mirror.baidu.com/pypi/simple 
不使用虚拟环境

**Comment by shiokaze** [comment]
> 月

目前没有提供这两个赛事的选项，目前只支持所有g1和第一年的g2,g3，第二年和第三年的g2和g3赛事之后会添加

**Comment by tlatixat** [comment]
> 目前没有提供这两个赛事的选项，目前只支持所有g1和第一年的g2,g3，第二年和第三年的g2和g3赛事之后会添加
好的,作者辛苦了,期待你的更新.
米浴第二场春季锦标赛因为有粉丝限制,所以不加的话米浴出道及退役,然后自定义里她适合的op赛都还没有,我看看让她跑其他的能不能绕过粉丝限制.
