### ISSUE TITLE
明明有croniter这个依赖，但是运行run.ps1时却报错说没有

### ISSUE THREAD

**Issue by kano177** [shiokaze/UmamusumeAutoTrainer#31]
在运行run.ps1这步的时候出了问题，我无论是在py3.10/libs里还是在venv里都有croniter这个依赖项，但是运行时会报错，环境变量也设置好了，请问是为什么呀![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/89f7e895-ea08-4027-8d82-e1dc579f5423)

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/b013260e-09a0-47c6-a848-4e4f1b2e50b0)

**Comment by shiokaze** [comment]
那继续执行python main.py会报错吗

**Comment by kano177** [comment]
难道是因为我放在桌面了？

**Comment by kano177** [comment]
有报错，和上面一样。
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/49010102-ce29-467e-af42-4af5d5876612)

**Comment by shiokaze** [comment]
python版本是什么？

**Comment by kano177** [comment]
是3.10.9，我删了venv之后重新install，结果出了两种报错，满屏的。这是为什么，下午我看一个报错都没有。
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/4281abd5-8c75-4085-b9e4-a57a1980ca03)

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/2263e7b5-0eda-4f69-912d-08279fc7c96b)

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/c58c5ea1-17f3-4e4f-9558-64c01907498f)

**Comment by shiokaze** [comment]
下载超时了，看上去网速有点慢

**Comment by kano177** [comment]
刚刚网速不好，重下了一遍，发现有几个依赖因为版本问题需要单独拎出来用pip install XXX --use-pep517
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/8039c522-f31d-41fe-8469-eaa23851cdc0)

但是这些都下好之后运行还是缺少crontier，尝试用上面这个方法安装就报错了

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/343c941a-1d7a-46a2-b50e-d312fac2d84a)

还有就是pip版本需要更新吗

**Comment by kano177** [comment]
venv里面明明是没有crontier ，但是我pip list里却有这个依赖。

**Comment by shiokaze** [comment]
参考一下这个
https://blog.csdn.net/nyist_yangguang/article/details/106262401

**Comment by kano177** [comment]
我把py路径下的croniter粘贴到venv里可以吗

**Comment by kano177** [comment]
使用命令pip install --target=C:\Users\15707\Desktop\UmamusumeAutoTrainer-main\venv\Lib\site-packages croniter==1.3.7 后终于在venv里下到了这个东西。
再次运行run.ps1出现这个界面，是正常运行了吗。
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/5b010567-476d-44ed-bc81-1d63fbd791c0)

**Comment by shiokaze** [comment]
是的

**Comment by kano177** [comment]
使用pip install --target=C:\Users\15707\Desktop\UmamusumeAutoTrainer-main\venv\Lib\site-packages croniter==1.3.7后成功安装了。
运行run.ps1也没报错了
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/0969500f-be51-4e45-9522-93f57b12f147)

**Comment by kano177** [comment]
又有一个问题啦.UAT running on http://127.0.0.1:8071复制到浏览器中访问打不开web ui
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/e3b7defc-6d34-4dc5-9404-60cd0d18980d)

**Comment by shiokaze** [comment]
http://127.0.0.1:8071 就行了
