### ISSUE TITLE
育成完成后不能再进行下一次育成吗

### ISSUE THREAD

**Issue by kano177** [shiokaze/UmamusumeAutoTrainer#32]
如题，没有在源文件中找到可以多次育成的设置

**Comment by kano177** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/9c5a489e-00b7-4d53-92ab-c10a787dab62)

**Comment by shiokaze** [comment]
可以一次创建多个育成任务

**Comment by kano177** [comment]
哦哦，那tp不足时会自动回复吗，我看点了否

**Comment by shiokaze** [comment]
暂时不能自动回tp

**Comment by kano177** [comment]
了解了
