### ISSUE TITLE
run.ps1执行失败

### ISSUE THREAD

**Issue by ZoeC5** [shiokaze/UmamusumeAutoTrainer#33]
install.ps1执行成功
.\venv\Scripts\activate执行成功
python main.py执行失败如图
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/19951317/c3083c12-ce7b-4548-9064-2e8b873fa4e8)

**Comment by PHY4L** [comment]
遇到这个问题+1，因为我用的py3.9，本打算升到3.10试一下再问。

**Comment by shiokaze** [comment]
升级python版本，你现在用的版本不支持这种语法

**Comment by ZoeC5** [comment]
> 升级python版本，你现在用的版本不支持这种语法

是这个问题，感谢。当时我安装python3.10看到有勾个path选项安装完就没管了。实际上我的电脑以前装过3.8，看version还是3.8的
