### ISSUE TITLE
状态: 5 (系统异常)

### ISSUE THREAD

**Issue by Crassrer** [shiokaze/UmamusumeAutoTrainer#34]
![屏幕截图(88)](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144516581/5367e904-ddca-4406-ac3e-aae678b50e84)
![屏幕截图(89)](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144516581/7df8da3a-72e4-4c84-beea-97701732329c)
不知道该咋整

**Comment by shiokaze** [comment]
没连上模拟器，检查一下模拟器的adb端口和配置里填的是不是一样的，如果是的话可以尝试重启下模拟器

**Comment by Crassrer** [comment]
感谢，是adb端口的问题，6&X版本是127.0.0.1:7555
