### ISSUE TITLE
网页打开正常，但是不能创建任务，无法确认。ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by bsyj** [shiokaze/UmamusumeAutoTrainer#36]
依赖正常安装，运行run .ps1，正常弹出UAT running on http://127.0.0.1:8071，打开网址后，创建任务无法点击确认，控制台报错
<img width="1280" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/124576831/ae7d068d-40a1-4687-936f-3abbfc19b3c6">
<img width="1280" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/124576831/b7669fe6-7eff-4611-b027-69553b065df4">

**Comment by shiokaze** [comment]
使用最新的代码

**Comment by bsyj** [comment]
卸载重装仍无法确定
<img width="1280" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/124576831/2ed7f849-d670-47bf-a3dc-41f28544c05c">

**Comment by shiokaze** [comment]
你这个webui看上去是很早之前的版本？试一下刷新浏览器缓存

**Comment by bsyj** [comment]
刷新浏览器缓存解决，感谢
<img width="1280" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/124576831/70a2bea9-0ced-4622-8f23-410022a7157f">
