### ISSUE TITLE
run运行失败

### ISSUE THREAD

**Issue by feng1149** [shiokaze/UmamusumeAutoTrainer#37]
运行时一直显示图中问题，麻烦大佬看一下要怎么弄才能运行，小白一个，望谅解
![1694275032059](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144549348/42303c50-5d02-464c-b225-21d3674917cd)

**Comment by shiokaze** [comment]
先使用install.ps1安装依赖再执行run.ps1

**Comment by feng1149** [comment]
> 先使用install.ps1安装依赖再执行run.ps1

已解决，谢谢大佬

**Comment by feng1149** [comment]
> 先使用install.ps1安装依赖再执行run.ps1

大佬还有个问题，我借卡要用新出的小栗帽，但uat里面没有可以选这个卡，只能等后续更新才有了吗

**Comment by shiokaze** [comment]
是的，可以手动选好了之后在启动
