### ISSUE TITLE
环境配置出错

### ISSUE THREAD

**Issue by lxyabc98** [shiokaze/UmamusumeAutoTrainer#4]
![{A68B3450-8AC0-4faa-9BE7-69B10F21F495}](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/92701713/8e0a47da-c348-45ce-8ce5-e3e85ee18d80)

**Comment by jkf123cn** [comment]
http://127.0.0.1:8071拒接访问

**Comment by shiokaze** [comment]
使用的python版本是什么

**Comment by shiokaze** [comment]
> [http://127.0.0.1:8071拒接访问](http://127.0.0.1:8071%E6%8B%92%E6%8E%A5%E8%AE%BF%E9%97%AE)

是否启动了程序

**Comment by lxyabc98** [comment]
> 使用的python版本是什么

3.11.4

**Comment by shiokaze** [comment]
换成3.10.9

**Comment by lxyabc98** [comment]
> 换成3.10.9

anaconda换3.10.12后正常运行
