### ISSUE TITLE
清华源出问题了？

### ISSUE THREAD

**Issue by inbrace419** [shiokaze/UmamusumeAutoTrainer#40]
pip install pyelftools==0.29 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pdf2docx==0.5.6 -i https://pypi.tuna.tsinghua.edu.cn/simple
这两句已经没用了。改用官方源下载正常。

**Comment by shiokaze** [comment]
我这里可以正常下载，可能是网络环境的问题
