### ISSUE TITLE
新更新的借用支援卡貌似无法选择

### ISSUE THREAD

**Issue by EastMG** [shiokaze/UmamusumeAutoTrainer#43]
<img width="233" alt="image" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/49364679/cd03640f-4f8b-43c8-8c64-ef0c5bce8dd4">

完全重新 git 一遍还是这样，选项框里没有新卡

**Comment by shiokaze** [comment]
清理一下浏览器缓存试试

**Comment by EastMG** [comment]
> 清理一下浏览器缓存试试

破案了就是缓存问题 (*/ω＼*)
