### ISSUE TITLE
用了新功能 "仅学习上述技能"勾选后出bug

### ISSUE THREAD

**Issue by tlatixat** [shiokaze/UmamusumeAutoTrainer#46]
![1](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/73833770/4585f4ed-9285-4ed6-ba2a-085fd6a67f9d)
找一遍没发现目标技能后会退出,但因为技能点数到达要求会再进去,然后再退出,无限循环.

**Comment by shiokaze** [comment]
使用的是最新的版本吗？之前的某个commit有这个问题，但是之后修复了

**Comment by shiokaze** [comment]
是稳定出现的吗？因为我这里刚试了下没问题

**Comment by tlatixat** [comment]
> 是稳定出现的吗？因为我这里刚试了下没问题

目前只出现一次,然后我下个脚本就取消这个选项了,一会儿我再试试.

**Comment by tlatixat** [comment]
奇怪,我跑了三个这个问题也触发不出来,更新一下后又跑了俩也是.
不过倒是遇到了其他的问题

重炮第二年4月后芙洛拉锦标赛和青叶奖,因为青叶奖会被标推荐窜到第一位,结果脚本点的是变成第二位的芙洛拉锦标赛

选择仅学习技能和预设点数后,第二次点数到达预设目标却不会让脚本点进去学习技能,而是忽略掉继续往下走.
不知道是不是因为我这边正番和点数达标同时出现的关系.

**Comment by shiokaze** [comment]
> 奇怪,我跑了三个这个问题也触发不出来,更新一下后又跑了俩也是. 不过倒是遇到了其他的问题
> 
> 重炮第二年4月后芙洛拉锦标赛和青叶奖,因为青叶奖会被标推荐窜到第一位,结果脚本点的是变成第二位的芙洛拉锦标赛
> 
> 选择仅学习技能和预设点数后,第二次点数到达预设目标却不会让脚本点进去学习技能,而是忽略掉继续往下走. 不知道是不是因为我这边正番和点数达标同时出现的关系.

这两个的比赛的问题了解了，刚看了下是我把比赛id填反了

**Comment by shiokaze** [comment]
已修复

**Comment by tlatixat** [comment]
![1](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/73833770/46bcf71e-5360-435f-99a7-9bc2e54976a4)
奇怪,它又出现了,这次我翻到开始的地方截了个图

**Comment by tlatixat** [comment]
不停止脚本手动干预继续下一回合后它还是会出现这种情况,最后到养成结束学技能也是如此,直接放弃技能点结束养成.
感觉好像是点进技能界面后跳过识别技能阶段又退出来了.

**Comment by shiokaze** [comment]
修复了
