### ISSUE TITLE
点run.ps1后显示这个窗口就关闭了是怎么回事

### ISSUE THREAD

**Issue by miseryrua** [shiokaze/UmamusumeAutoTrainer#5]
求教，谢谢
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/86465463/e4dbd978-186a-4016-a9f0-9282d0fb57d7)

**Comment by shiokaze** [comment]
pip安装依赖没有成功，删除venv文件夹后重新运行install.ps1，看是否有报错
