### ISSUE TITLE
每次启动都报错，一闪而过，’type' object is not subscriptable

### ISSUE THREAD

**Issue by jw86215361** [shiokaze/UmamusumeAutoTrainer#50]
大佬快帮忙看看啥问题呢

**Comment by jw86215361** [comment]
![244aef1bcd099c162b7f4cd0ad61c9e](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/24265213/e63e55e6-0732-4690-a719-647dcda0ce98)

**Comment by shiokaze** [comment]
升级python版本
