### ISSUE TITLE
无法启动 PaddleOCR inference.pdmodel

### ISSUE THREAD

**Issue by EastMG** [shiokaze/UmamusumeAutoTrainer#52]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/49364679/14eddeb9-918a-43cf-a34e-442be0e0a5ec)

`RuntimeError: (NotFound) Cannot open file C:\Users\孟令宇/.paddleocr/whl\det\ml\Multilingual_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.`
`[Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1500)`

会不会是中文路径的问题 (￣▽￣)"

**Comment by shiokaze** [comment]
参考https://github.com/shiokaze/UmamusumeAutoTrainer/issues/18
