### ISSUE TITLE
未检测到图像，刚才还好好的。。

### ISSUE THREAD

**Issue by Dunzuzhang** [shiokaze/UmamusumeAutoTrainer#53]
呜呜呜呜呜

**Comment by shiokaze** [comment]
https://github.com/shiokaze/UmamusumeAutoTrainer/issues/10
参考这个看下是不是类似的问题

**Comment by Dunzuzhang** [comment]
> #10 参考这个看下是不是类似的问题

非常感谢~~真的很好用，我重新安装了一次就好了，可能是我之前修改了什么配置，然后我忘却修改什么了，保后台也关了，但是还是不行，但是重装一次模拟器后就好了。

**Comment by shiokaze** [comment]
ok
