### ISSUE TITLE
关于历战马和赛程选项

### ISSUE THREAD

**Issue by Aroudight-mo** [shiokaze/UmamusumeAutoTrainer#55]
想用于历战种马的养成，但发现网页选项只有一部分赛事。翻找发现了比赛对应数字的表，按照表添加之后也没用，然后就out of range了，希望能添加更多的比赛选项或者增加自行按照表格添加赛程的方法orz

**Comment by shiokaze** [comment]
可以将对应赛事的图片保存到resource/umamusume/race目录下即可，因为这部分工作量较大所以目前只提供了一些常用的比赛

**Comment by Aroudight-mo** [comment]
嗯，我提出问题的原因是因为自己添加图片测试也失败了，不过那是大概一周之前的版本，现在我再测试一下

**Comment by Timmy-web** [comment]
> 嗯，我提出问题的原因是因为自己添加图片测试也失败了，不过那是大概一周之前的版本，现在我再测试一下

我测试了新版本，也是找不到目标赛事，我在预设json里添加了赛事，然后在图片里也添加了race.csv里对应的赛程id，好像也是不行，你这边测试通过后，看看能不能分享下办法

**Comment by shiokaze** [comment]
添加一个赛事的完整步骤大概是这样
1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事

**Comment by Timmy-web** [comment]
> 添加一个赛事的完整步骤大概是这样
> 
> 1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
> 2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
> 3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
> 4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
> 5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事

这些步骤都做完了，网页倒是更新能显示比赛了，不过在运行的时候还是无法识别我放进去的图片，我图片截图的是png格式，类似文件夹其他图片的截法，也还是不行。
像这样![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/54231170/63d7097f-44b8-4cbb-9891-e6b77c63a56f)

**Comment by shiokaze** [comment]
> > 添加一个赛事的完整步骤大概是这样
> > 
> > 1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
> > 2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
> > 3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
> > 4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
> > 5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事
> 
> 这些步骤都做完了，网页倒是更新能显示比赛了，不过在运行的时候还是无法识别我放进去的图片，我图片截图的是png格式，类似文件夹其他图片的截法，也还是不行。 像这样![image](https://user-images.githubusercontent.com/54231170/268512045-63d7097f-44b8-4cbb-9891-e6b77c63a56f.png)

可以注意一下截屏时模拟器分辨率是否是720*1280，不仅是模拟器本身，而且窗口的分辨率也需要一致

**Comment by Timmy-web** [comment]
> > > 添加一个赛事的完整步骤大概是这样
> > > 
> > > 1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
> > > 2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
> > > 3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
> > > 4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
> > > 5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事
> > 
> > 
> > 这些步骤都做完了，网页倒是更新能显示比赛了，不过在运行的时候还是无法识别我放进去的图片，我图片截图的是png格式，类似文件夹其他图片的截法，也还是不行。 像这样![image](https://user-images.githubusercontent.com/54231170/268512045-63d7097f-44b8-4cbb-9891-e6b77c63a56f.png)
> 
> 可以注意一下截屏时模拟器分辨率是否是720*1280，不仅是模拟器本身，而且窗口的分辨率也需要一致

是以模拟器本身的720*1080为基础去截图么，因为我现在是截图完之后，对比了下图片的分辨率，感觉都差不多，也没有过大或者过小。所以有点懵
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/54231170/75b588da-90fa-4511-b03b-d5d3311eb82d)

**Comment by shiokaze** [comment]
> > > > 添加一个赛事的完整步骤大概是这样
> > > > 
> > > > 1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
> > > > 2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
> > > > 3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
> > > > 4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
> > > > 5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事
> > > 
> > > 
> > > 这些步骤都做完了，网页倒是更新能显示比赛了，不过在运行的时候还是无法识别我放进去的图片，我图片截图的是png格式，类似文件夹其他图片的截法，也还是不行。 像这样![image](https://user-images.githubusercontent.com/54231170/268512045-63d7097f-44b8-4cbb-9891-e6b77c63a56f.png)
> > 
> > 
> > 可以注意一下截屏时模拟器分辨率是否是720*1280，不仅是模拟器本身，而且窗口的分辨率也需要一致
> 
> 是以模拟器本身的720*1080为基础去截图么，因为我现在是截图完之后，对比了下图片的分辨率，感觉都差不多，也没有过大或者过小。所以有点懵 ![image](https://user-images.githubusercontent.com/54231170/268512446-75b588da-90fa-4511-b03b-d5d3311eb82d.png)

就是截屏时模拟器窗口（不包括工具栏以及侧边栏，仅包括安卓系统的画面）为720*1280，模板图片本身长宽大小不要太大就行，没有严格的要求，如果还是找不到，可能是你开了模拟器画面滤镜或者类似的功能导致颜色显示颜色与实际颜色不一致就会出现识别不到的问题

**Comment by Timmy-web** [comment]
> > > > > 添加一个赛事的完整步骤大概是这样
> > > > > 
> > > > > 1. 先在resource/umamusume/data/race.csv里面找到你要添加的赛事的id
> > > > > 2. 把赛事图片保存到resource/umamusume/race，图片只需要包括赛事名字即可，长宽不需要太大，名称为赛事id
> > > > > 3. 在web/src/components/taskeditmodal.vue内找到umamusumeRaceList，一共三个列表对应三年，按照里面的json格式添加id,赛事名，日期以及赛事类型
> > > > > 4. 使用npm run build 打包前端，如果只是想临时用，可以npm run dev， 在127.0.0.1:5173下调试
> > > > > 5. 如果上一步build了，把web/dist内的内容复制到public文件夹内，刷新127.0.0.1:8071即可看到新添加的赛事
> > > > 
> > > > 
> > > > 这些步骤都做完了，网页倒是更新能显示比赛了，不过在运行的时候还是无法识别我放进去的图片，我图片截图的是png格式，类似文件夹其他图片的截法，也还是不行。 像这样![image](https://user-images.githubusercontent.com/54231170/268512045-63d7097f-44b8-4cbb-9891-e6b77c63a56f.png)
> > > 
> > > 
> > > 可以注意一下截屏时模拟器分辨率是否是720*1280，不仅是模拟器本身，而且窗口的分辨率也需要一致
> > 
> > 
> > 是以模拟器本身的720*1080为基础去截图么，因为我现在是截图完之后，对比了下图片的分辨率，感觉都差不多，也没有过大或者过小。所以有点懵 ![image](https://user-images.githubusercontent.com/54231170/268512446-75b588da-90fa-4511-b03b-d5d3311eb82d.png)
> 
> 就是截屏时模拟器窗口（不包括工具栏以及侧边栏，仅包括安卓系统的画面）为720*1280，模板图片本身长宽大小不要太大就行，没有严格的要求，如果还是找不到，可能是你开了模拟器画面滤镜或者类似的功能导致颜色显示颜色与实际颜色不一致就会出现识别不到的问题

问题解决了

**Comment by Tilie** [comment]
虽然有些不合适，但是想问.
如果逆向那些付费脚本，得到的资源文件是否可用于本项目使用。
我解包过，可以直接找到相应的原始图片.

**Comment by shiokaze** [comment]
> 虽然有些不合适，但是想问.
> 如果逆向那些付费脚本，得到的资源文件是否可用于本项目使用。
> 我解包过，可以直接找到相应的原始图片.

这部分工作量主要来自对齐前后端比赛id和验证，获取模板图片本身不需要太多时间，所以这么做没必要也不合适。
最近问历战的功能比较多，我也会尽快完成这部分缺失赛程的添加
