### ISSUE TITLE
【BUG】休息时不会点击“确认”键，由于反复点击“休息”而卡死在休息前阶段

### ISSUE THREAD

**Issue by 17876zjc** [shiokaze/UmamusumeAutoTrainer#57]
![{~B`QS`QOA$B)9J142G3 HP](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/92a8c8d8-f601-4957-881d-9fec8a7e6880)
## 复现方式
不明，疑似每一次休息时稳定复现
## 表现形式
脚本尝试反复点击“休息”，但是不会点击“确认”。第二次休息将游戏界面返回至确认之前，从而卡死在休息前阶段。在点击任意其它界面后（比如点击“设置”再点击“返回”）脚本便能正常点击“休息”+“确认”

**Comment by shiokaze** [comment]
看下是不是使用了简易版画质或者其他影响了画面的选项

**Comment by 17876zjc** [comment]
> 看下是不是使用了简易版画质或者其他影响了画面的选项

确认了是标准版画质
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/3dfeb3bb-5dac-4fa9-8bd0-328c51e98c3e)
这是我的模拟器显示设置：
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/e6d67b40-170a-4d91-8700-99e938153d05)

**Comment by 17876zjc** [comment]
当然也可以通过取消休息/外出/医务室的确认提示消灭这个bug XD

**Comment by shiokaze** [comment]
下面的显存优化选项选择的是第一个吗

**Comment by shiokaze** [comment]
> 当然也可以通过取消休息/外出/医务室的确认提示消灭这个bug XD

这样是比较推荐的，可以提高效率。但是我一直都是打开提示框的，每天挂着也没发现这个问题

**Comment by 17876zjc** [comment]
> 下面的显存优化选项选择的是第一个吗
是这个吗？
![Uploading image.png…]()

**Comment by shiokaze** [comment]
> > 下面的显存优化选项选择的是第一个吗
> 
> 是这个吗？ ![image](https://user-images.githubusercontent.com/35091817/268601512-3de09d1a-6cb7-4d90-8274-ce281285254c.png)

改为第二个试试

**Comment by 17876zjc** [comment]
好，我下一把再观察一下

**Comment by 17876zjc** [comment]
还发现了无法识别技能的问题，不知道是不是同样的原因
如果还有的话我再水一个issue（

**Comment by 17876zjc** [comment]
> > > 下面的显存优化选项选择的是第一个吗
> > 
> > 
> > 是这个吗？ ![image](https://user-images.githubusercontent.com/35091817/268601512-3de09d1a-6cb7-4d90-8274-ce281285254c.png)
> 
> 改为第二个试试

看起来解决了，技能也能正常点了

作者你真是我爹😭我手养了三周没一个3星蓝因子，你的脚本挂了第一把就爆了个3速
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/b6fc5257-ac4c-40a5-8956-24214c18f000)

已经叫上小伙伴给你点star了👍

**Comment by shiokaze** [comment]
ok
