### ISSUE TITLE
现在养马设置的属性目标有起作用吗？

### ISSUE THREAD

**Issue by ZJChe** [shiokaze/UmamusumeAutoTrainer#64]
实际观察了一下，到了游戏后期还是在执行哪里亮了点哪里的策略，只选择收益最高的一个训练。但实际上我想养历战马刷因子的话，不是很在乎最后总体评分有多高， 关键的是力速耐都要600。这样到育成中后期完全可以选择不点彩圈而点别的/休息以达成设置的属性目标。

现在好像只要稍微运气差一点，彩圈多跑错几次位置，最后就容易无法达成属性目标。甚至有一次带了4速2耐，耐力拉到了700，速度只有500，ura都没打到

**Comment by ZJChe** [comment]
带的卡肯定是没问题的，不至于差到拉不起来属性值。同样的卡组我手养是能速力耐都600的，但是如果节奏把握不好确实容易有某个属性爆太多，所以我会在后期强行点没有彩圈或者没有人的训练去凑速力耐600

**Comment by shiokaze** [comment]
现在后期的策略简单来说是优先点提升属性值多的，但是如果属性值超过了目标属性，超过那一部分不会参与计算
出现这种情况一般是你设置的目标超过了你的支援卡强度，导致有优势/马自带加成的那种训练总是能比别的训练提升的多。就会一直点那个
这个你可以观察下每回合在控制台打印的回合期望，如果总是所有都超过了你的当前属性，说明设置的太高了

**Comment by shiokaze** [comment]
> 带的卡肯定是没问题的，不至于差到拉不起来属性值。同样的卡组我手养是能速力耐都600的，但是如果节奏把握不好确实容易有某个属性爆太多，所以我会在后期强行点没有彩圈或者没有人的训练去凑速力耐600

我考虑下之后增加一个评分优先和属性优先的选项来优化一下你说的这种情况

**Comment by ZJChe** [comment]
![2_JJ05DR3APR9SP8F3Z4384](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/341821e6-9d8c-4e09-a8aa-e8508f4863e0)

上面提到的是这次训练，继承是6速12耐，我这支援卡应该不至于速度拉不起来吧😇
设置的目标是650速600耐650力100根250智
最后有马都没打过，有马之前还在点耐，猜测是因为只有小海湾持续在线，别的5张卡都在逛街

**Comment by shiokaze** [comment]
> ![2_JJ05DR3APR9SP8F3Z4384](https://user-images.githubusercontent.com/35091817/269166667-341821e6-9d8c-4e09-a8aa-e8508f4863e0.png)
> 
> 上面提到的是这次训练，继承是6速12耐，我这支援卡应该不至于速度拉不起来吧😇 设置的目标是650速600耐650力100根250智

如果是历战马的话，因为训练占比比较低，确实有可能出现方差比较大的情况的

**Comment by ZJChe** [comment]
好像很有道理，那我把比赛弄少点看看行不行

**Comment by ZJChe** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/fe88ca02-3bda-4a4f-8054-79149ac0f9f0)
依然是观察到了这个问题，在速度远超过设置目标，力量远不足于目标时，还是点了2彩圈的速度训练而非1彩圈的力量训练

**Comment by shiokaze** [comment]
> ![image](https://user-images.githubusercontent.com/35091817/269198279-fe88ca02-3bda-4a4f-8054-79149ac0f9f0.png)
> 依然是观察到了这个问题，在速度远超过设置目标，力量远不足于目标时，还是点了2彩圈的速度训练而非1彩圈的力量训练

可能是速度附带的力量提升比直接点力量收益大导致的

**Comment by ZJChe** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/181e1007-7fdd-45aa-b609-0b223d473091)
虽然最后打完ura决赛惊险完成了目标。。。不过考虑到脚本的容错空间，不是每一把都能打到ura决赛的

**Comment by ZJChe** [comment]
> > ![image](https://user-images.githubusercontent.com/35091817/269198279-fe88ca02-3bda-4a4f-8054-79149ac0f9f0.png)
> > 依然是观察到了这个问题，在速度远超过设置目标，力量远不足于目标时，还是点了2彩圈的速度训练而非1彩圈的力量训练
> 
> 可能是速度附带的力量提升比直接点力量收益大导致的

点力量还能带来耐力的收益嘞，我耐力也没有达成目标

**Comment by shiokaze** [comment]
> > > ![image](https://user-images.githubusercontent.com/35091817/269198279-fe88ca02-3bda-4a4f-8054-79149ac0f9f0.png)
> > > 依然是观察到了这个问题，在速度远超过设置目标，力量远不足于目标时，还是点了2彩圈的速度训练而非1彩圈的力量训练
> > 
> > 
> > 可能是速度附带的力量提升比直接点力量收益大导致的
> 
> 点力量还能带来耐力的收益嘞，我耐力也没有达成目标

看图里是已经满足了，注意这里说的是此回合的耐力目标，不是总体目标

**Comment by ZJChe** [comment]
我体感上感觉怪怪的，但是没有记录下来证据。晚上我再开一把观察一下吧

**Comment by shiokaze** [comment]
> 我体感上感觉怪怪的，但是没有记录下来证据。晚上我再开一把观察一下吧

可以多跑几匹马验证一下给些建议，这里逻辑和算法肯定是有提升空间的，如果有更好的代码改进也欢迎提交pr

**Comment by Tilie** [comment]
> > 带的卡肯定是没问题的，不至于差到拉不起来属性值。同样的卡组我手养是能速力耐都600的，但是如果节奏把握不好确实容易有某个属性爆太多，所以我会在后期强行点没有彩圈或者没有人的训练去凑速力耐600
> 
> 我考虑下之后增加一个评分优先和属性优先的选项来优化一下你说的这种情况

也许并不需要专门的评分优先和属性有限的策略改动？
我在#68的议题中，提到阶段性目标。是否可以将超过阶段性目标的属性的逻辑，从忽略超过部分改为，超过部分越多评分降低。这样就可以达到该议题的效果？这样代码改动逻辑应该最小。

**Comment by shiokaze** [comment]
> > > 带的卡肯定是没问题的，不至于差到拉不起来属性值。同样的卡组我手养是能速力耐都600的，但是如果节奏把握不好确实容易有某个属性爆太多，所以我会在后期强行点没有彩圈或者没有人的训练去凑速力耐600
> > 
> > 
> > 我考虑下之后增加一个评分优先和属性优先的选项来优化一下你说的这种情况
> 
> 也许并不需要专门的评分优先和属性有限的策略改动？ 我在#68的议题中，提到阶段性目标。是否可以将超过阶段性目标的属性的逻辑，从忽略超过部分改为，超过部分越多评分降低。这样就可以达到该议题的效果？这样代码改动逻辑应该最小。

阶段性目标的想法是可以的，可以针对养成中某个容易翻车的比赛针对训练。但是后半提到的算法逻辑实际上是很难量化的，具体超过多少降低多少呢？
另外，其实这些翻车的问题在北黑出来之后都会解决，力大砖飞

**Comment by zylbmrx** [comment]
超了目标,得分减半,超了(比如说10%)直接不点对应训练完事,养种马突出一个水桶

这个策略加个开关,加个配置(上文的10%),养种马专用

**Comment by ZJChe** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/89a0b4b1-fd03-4c4f-bf00-7d3e3cc3f0e8)

刚刚观察到了在速度和力量都满了的情况下，还是点了速度训练。速度训练有2个彩圈，耐力和力量都没彩圈
这肯定是有问题了

**Comment by shiokaze** [comment]
> ![image](https://user-images.githubusercontent.com/35091817/269630223-89a0b4b1-fd03-4c4f-bf00-7d3e3cc3f0e8.png)
> 
> 刚刚观察到了在速度和力量都满了的情况下，还是点了速度训练。速度训练有2个彩圈，耐力和力量都没彩圈 这肯定是有问题了

看了下代码确实有问题，这里之前考虑是ura期间比赛胜利会给50点左右的属性，实际上目标属性在参与计算时会被预先减去50点，没有考虑到到了ura还没有达到或者快要达到属性的情况，仍然会按去掉50点的情况去算。
所以你发现的这种情况是因为脚本计算时的目标属性实际上是[600,550,600,50,250]，在它认为所有的属性都已经满足了，所以选择了加成最高的
可以先给每个目标属性提高50点来解决

**Comment by ZJChe** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/bda89c91-0551-430c-9b6d-f938431e1032)

那这种情况呢，为什么还是点了速度？
点速度加的力量是9，点力量是+12力，还附带加了一些耐力

![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/5f17c18c-8fdd-4a0f-b12c-5bf285d41c05)
后面又点了一次

**Comment by shiokaze** [comment]
> ![image](https://user-images.githubusercontent.com/35091817/269641323-bda89c91-0551-430c-9b6d-f938431e1032.png)
> 
> 那这种情况呢，为什么还是点了速度？ 点速度加的力量是9，点力量是+12力，还附带加了一些耐力
> 
> ![image](https://user-images.githubusercontent.com/35091817/269642386-5f17c18c-8fdd-4a0f-b12c-5bf285d41c05.png) 后面又点了一次

因为除了训练本身有权重，参与训练的支援卡，训练设施，技能点数的提升也是有各自权重的
根据你发的图片猜测，第一次点了速度，是因为速度和力量训练提升的力量差不多，但是速度训练给了更多的技能点，所以选择了速度训练，第二次点了速度，是因为速度那边的支援卡（没有满4格好感的支援卡或者是没有满好感的理事长/记者）占比很高
