### ISSUE TITLE
现在的ocr函数有些汉字认不出来

### ISSUE THREAD

**Issue by ZJChe** [shiokaze/UmamusumeAutoTrainer#67]
![1](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/c2df4f00-2b8c-456a-8a09-6ec075dec9c1)
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/cb27ee91-197d-459b-9ba9-d346014ab77c)
当该技能被指定为优先学习时，这会导致无法匹配到它而点不到这个技能。

暂不清楚是否有其它技能或者汉字也会有这个问题

**Comment by shiokaze** [comment]
这个没办法，ocr库的能力有限
目前是会进行模糊匹配的，遇到差的特别多的情况考虑之后针对这部分技能使用图片匹配代替

**Comment by ZJChe** [comment]
唉这样搞也很麻烦，维护和更新数据库又是个大工程。最好能做得易于拓展，除非是特别关键的地方否则是不太愿意特殊处理的

我看这个文字也挺清楚的，我试一试不知道能不能找到更好的针对汉字的ocr库

**Comment by shiokaze** [comment]
这个完全没必要纠结，真正用到的技能很少，大赛马的种马要求的其实就几个关键技能的白因子而已，如果遇到问题完全可以针对这几个进行特殊处理。而且支援卡强度/种马因子上来之后育成过程基本不点技能，维护巨大的技能库最后也是用不到多少的

**Comment by ZJChe** [comment]
那听你的，我没玩过后面大赛的版本，不知道要点什么技能😄
