### ISSUE TITLE
所有属性都达到目标后，导致点训练时错误判断

### ISSUE THREAD

**Issue by ZJChe** [shiokaze/UmamusumeAutoTrainer#69]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/db7087b4-463f-483d-b0b1-29f180708011)

根据日志，看上去是超出目标越多，属性增长得分越低？由于负反馈最后点了收益最小的毅力训练。实际上属性全部达标后应该还是应该按照收益最大化点训练，不需要负反馈了

**Comment by shiokaze** [comment]
已修复
