### ISSUE TITLE
养成目标达成后报错及部分问题

### ISSUE THREAD

**Issue by lxyabc98** [shiokaze/UmamusumeAutoTrainer#7]
![{6B23602C-12C4-471f-9A26-22CEF1B385C4}](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/92701713/9c596a21-ca0b-42c9-8f11-b96c3a610219)
1. 养成目标达成后报错
不清楚是暂时没有写ura相关还是bug
2. 实际选项与目标数值差距大
如图，1000的目标速度但1200
3. 技能相关（模版都是空）
目前是精准检索（得把所有需要的协助卡和继承技能都写上去）还是有部分匹配（比如填入中距离，战术：领跑可以选择技能描述中包含中距离/战术：领跑的技能）。

**Comment by shiokaze** [comment]
1. 应该是满速之后数字变成了max导致的类型转换错误，这个我修复一下
2. 与目标数值差距大，这个算法目前还需要优化，出现这个问题的主要原因是智力训练本身面板低导致ai认为提升速度对目标的提升更大，就会优先去提升速度。
3. 技能现在是全部匹配名称，需要填上完整的技能名

**Comment by shiokaze** [comment]
已修复
