### ISSUE TITLE
在较低帧率下，滑动指令失效的相关问题。

### ISSUE THREAD

**Issue by Tilie** [shiokaze/UmamusumeAutoTrainer#70]
在学习技能的相关界面，有一上滑返回列表顶部的操作。
若在较低帧率的情况下（fps<=20）,非导致无法识别到向上滑动的行为。
修复方案是增大滑动时间，即cultivate.py的第356行.
`ctx.ctrl.swipe(x1=23, y1=620, x2=23, y2=1000, duration=100, name="")`
duration更改为500。可解决问题

疑问：直接返回上一界面，重新进入技能界面是否为重置技能列表的更优雅的实现方式？

**Comment by ZJChe** [comment]
500也太久了，不知道有没有办法监测到当前环境的帧率针对性地调整？

关于重置技能列表，会在什么条件下用到这个功能？

**Comment by ZJChe** [comment]
> 关于重置技能列表，会在什么条件下用到这个功能？

如果你指的是返回页面顶部是重置技能列表，在最新的dev分支里我已经把它优化掉了，现在在返回页面顶部的过程中就可以点好技能

另外这个duration=100的快速上划，也已经没有了，所有的划动都是duration=1000的

可以pull一下看看我改好的代码

**Comment by Tilie** [comment]
哦哦，原来已经改了，不好意思。
