### ISSUE TITLE
训练是图片识别失败

### ISSUE THREAD

**Issue by Kanade-nya** [shiokaze/UmamusumeAutoTrainer#71]
进入训练页面就会这样。。
<img width="1259" alt="屏幕截图 2023-09-23 192825" src="https://github.com/shiokaze/UmamusumeAutoTrainer/assets/96279451/bcb77559-9843-43e5-9b86-43a3df8592d2">

**Comment by ZJChe** [comment]
python版本是3.10.9吗？我之前用低版本出现过类似的问题，需要更新一下python

可以在Powershell或者cmd里用`python --version`查看版本

**Comment by shiokaze** [comment]
如果这个问题必定出现的话，检查一下python版本是否为3.10.9，paddleocr的版本是否为2.7.0.x，

**Comment by Kanade-nya** [comment]
之前用的是python 3.10.11 ，3.10.9重新运行一遍没有问题 。建议严格按照3.10.9来 其他版本可能有包因为版本问题不兼容
