### ISSUE TITLE
在运行run.ps1时出现的错误，如图

### ISSUE THREAD

**Issue by xlhl-yan** [shiokaze/UmamusumeAutoTrainer#73]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/127706999/c141a335-b19b-4076-9b49-32aaea0b4f4e)

**Comment by xlhl-yan** [comment]
重新克隆执行也是一样的问题

**Comment by shiokaze** [comment]
运行install.ps1成功了吗？

**Comment by xlhl-yan** [comment]
并没有成功

**Comment by shiokaze** [comment]
没有安装成功的话，可以提供下报错信息。
通常来说是python版本不正确，环境变量没配置，网络问题等，可以先根据readme里面的常见问题看看能不能解决

**Comment by xlhl-yan** [comment]
python版本与环境变量问题，已解决

**Comment by shiokaze** [comment]
ok
