### ISSUE TITLE
新年事件选项

### ISSUE THREAD

**Issue by ZJChe** [shiokaze/UmamusumeAutoTrainer#75]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/3e2d3228-0366-49bf-b71c-f20ba200bae3)

现在新年事件的选项是固定的还是会根据当前体力/属性判断？我第一次新年时体力是空的，但是还是选择了加属性的选项。这样下回合休息只要不是+70体，训练都是会有风险的。而且好像我记得加属性的选项收益是不如加技能点的吧？

**Comment by d-bluedreams** [comment]
目前事件的逻辑是什么？好像是不是没做事件选项分析，每次都是选第一个。

**Comment by shiokaze** [comment]
目前选项仅会选择第一个，暂时没有事件分析。
因为事件选项结果复杂，这里考虑是之后让使用者去填想要的事件的选项。不过新年等包含会体力选项的这类事件可以加个根据当前体力来判断选择合适的选项

**Comment by Timmy-web** [comment]
顺便说一下，扎针的事件默认建议选最保守的拒绝，刚刚开一把，还没出道，转个头心情直接极差，所有属性-15，直接开局天崩了

**Comment by ZJChe** [comment]
对的，感觉有几个重要的通用事件可以先做一下，

新年，扎针，大胃王

**Comment by shiokaze** [comment]
已支持

**Comment by ZJChe** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/901194d7-dcbc-493c-90ef-4d55511d5ad5)
好像还是没识别到的样子
