### ISSUE TITLE
run.ps1以powershell运行，打不开，直接双闪一下就没了

### ISSUE THREAD

**Issue by bailulail** [shiokaze/UmamusumeAutoTrainer#77]
遇到这种该怎么解决？

**Comment by bailulail** [comment]
控制台直接就闪一下就没了

**Comment by shiokaze** [comment]
先启动powershell控制台，进入到对应目录下使用 ./run.ps1启动就能看到闪退原因

**Comment by bailulail** [comment]
但是左边没有任何反应，是我没有安装好吗？打开，然后运行，然后直接闪一下，左边没有任何反应![IMG_20230926_204637.jpg](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144103351/916a0db8-7411-41e1-bc2a-f15f332bee91)

**Comment by shiokaze** [comment]
在左边的控制台内使用cd+路径命令进入右边的所在目录，在输入 ./run.ps1执行脚本，即可看到报错信息

**Comment by bailulail** [comment]
![IMG_20230926_211130.jpg](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/144103351/32c0ba5c-506f-44aa-b51f-1ffeb9cc450d)

啥原因？

**Comment by shiokaze** [comment]
检查是否用install.ps1安装成功了依赖，python版本是否是正确的3.10.9（必须严格的是这个版本）
一般来说出现这个问题，是你的python版本不对或者安装过程中有部分依赖包安装失败

**Comment by bailulail** [comment]
谢了老哥好了，换了一个地方，重新开始弄好了

**Comment by shiokaze** [comment]
ok
