### ISSUE TITLE
改了页面代码，但是不生效，请教一下要怎样配置才能读本地运行的vue

### ISSUE THREAD

**Issue by g0ngw0** [shiokaze/UmamusumeAutoTrainer#78]
改了页面代码，但是不生效，请教一下要怎样配置才能读本地运行的vue

**Comment by shiokaze** [comment]
在web文件夹下执行npm run dev后访问127.0.0.1:5173即可

**Comment by ZJChe** [comment]
@shiokaze 您好，我修改了一些前端代码，现在在127.0.0.1:5173里能看到更改了，请问怎么把变动应用到正式运行的版本里？

**Comment by shiokaze** [comment]
> @shiokaze 您好，我修改了一些前端代码，现在在127.0.0.1:5173里能看到更改了，请问怎么把变动应用到正式运行的版本里？

使用npm run build 后将产生的dist文件夹内文件移动到public内
