### ISSUE TITLE
目标属性为0会报错，有时存在选项点了没反应的情况，重启后run.ps恢复正常

### ISSUE THREAD

**Issue by YuanSnowing** [shiokaze/UmamusumeAutoTrainer#8]
1. 目标属性为0的时候会报错停止运行
2. 有时训练界面不能确认训练的属性，会产生死循环
![1693657116979](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/53067358/865ff276-f5a6-4510-90b2-bcf462457ca6)

**Comment by shiokaze** [comment]
1. 之后加个参数校验，可以先不填0，毕竟开局就有100的属性
2. 暂时没遇到过，这种重复点一个地方的可能是模拟器卡了导致传给脚本的图像没有变化

**Comment by YuanSnowing** [comment]
好的，刚刚我这儿还出现了其他的bug，也是会一直卡住。手动进入出道战之后恢复正常了。
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/53067358/61790e8d-2c05-43da-b14c-9e044563a22b)

**Comment by shiokaze** [comment]
> 好的，刚刚我这儿还出现了其他的bug，也是会一直卡住。手动进入出道战之后恢复正常了。 ![image](https://user-images.githubusercontent.com/53067358/265208449-61790e8d-2c05-43da-b14c-9e044563a22b.png)

已修复
