### ISSUE TITLE
BUG: 计算训练得分为nan，导致卡死

### ISSUE THREAD

**Issue by ZJChe** [shiokaze/UmamusumeAutoTrainer#80]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/35091817/bcda4053-7428-4978-8f63-67111358117b)

**Comment by ZJChe** [comment]
设置的目标数值是[ 700, 600, 600, 100, 300 ]，不知道是不是因为数值达标导致的异常

**Comment by ZJChe** [comment]
多试了几次，只要到最后所有属性都达标了就能稳定复现

**Comment by shiokaze** [comment]
已修复
