### ISSUE TITLE
运行install时出错

### ISSUE THREAD

**Issue by momings** [shiokaze/UmamusumeAutoTrainer#82]
![powershell_AIlMgHcoYl](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/114274988/9f6b27bc-e505-4fe7-a9c9-0d1be2b731d2)

安装了3.10.9python,在右键使用power shell运行时显示的窗口，请问一下该如何解决

**Comment by Aroudight-mo** [comment]
可以冲windows商店找到Python对应版本下载，应该就不会出这个问题了

**Comment by ZJChe** [comment]
请问打开一个cmd或者powershell后，执行`python`或者`python3`是否能正常运行？

如果报错找不到python的话，需要配置一下环境变量，请参考: https://www.php.cn/faq/471645.html

**Comment by momings** [comment]
已解决，感谢
