### ISSUE TITLE
请问怎么修改访问后端端口号

### ISSUE THREAD

**Issue by 2297146282** [shiokaze/UmamusumeAutoTrainer#83]
有2个号，想同时运行，修改了axiosConf.js种的beas.url后还是访问默认8071端口,看代码读取的不是baseurl，请问在哪里修改配置文件
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/71175137/ce1bb435-6f94-4068-ae34-5c23ca29bde0)

**Comment by shiokaze** [comment]
改的位置没错但是前端修改后需要使用npm run build重新打包后放入public文件夹才能正常使用
