### ISSUE TITLE
这个是啥问题 我路径也都是英文的

### ISSUE THREAD

**Issue by kirikoQAQ** [shiokaze/UmamusumeAutoTrainer#86]
.\venv\Scripts\activate : 无法将“.\venv\Scripts\activate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 C:\UmamusumeAutoTrainer-dev\run.ps1:1 字符: 1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
python : C:\Users\Kiriko\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\Kiriko\\main.py': [Errno 2] No such file or directory
所在位置 C:\UmamusumeAutoTrainer-dev\run.ps1:2 字符: 1
+ python main.py
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\Kiriko...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by ZJChe** [comment]
对于报错1：有没有先执行install.ps1？
对于报错2：检查一下环境变量中有没有绑定过main.py。如果不知道怎么检查环境变量的话，也可以用记事本打开run.ps1，把第二行改成`python .\main.py` 再试一试

**Comment by kirikoQAQ** [comment]
大桐DATONG
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shiokaze/UmamusumeAutoTrainer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shiokaze/UmamusumeAutoTrainer] 这个是啥问题 我路径也都是英文的 (Issue #86)





 
对于报错1：有没有先执行install.ps1？
 对于报错2：检查一下环境变量中有没有绑定过main.py。如果不知道怎么检查环境变量的话，可以用记事本打开run.ps1，把第二行改成python .\main.py 再试一试

**Comment by kirikoQAQ** [comment]
执行install报错1
pip :   error: subprocess-exited-with-error
所在位置 G:\UmamusumeAutoTrainer-dev\install.ps1:33 字符: 1
+ pip install pdf2docx==0.5.6 -i https://pypi.tuna.tsinghua.edu.cn/simp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  error: subprocess-exited-with-error:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
报错2
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
pip : ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
所在位置 G:\UmamusumeAutoTrainer-dev\install.ps1:34 字符: 1
+ pip install --upgrade -r requirements.txt -i https://mirror.baidu.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Could no...quirements.txt':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by ZJChe** [comment]
在powershell或者cmd里执行`python --version`和`pip --version`检查一下python和pip的版本

另外也请检查一下install.ps1所在目录里是不是有requirements.txt文件
