### ISSUE TITLE
运行install时出错

### ISSUE THREAD

**Issue by 0osmanthus** [shiokaze/UmamusumeAutoTrainer#87]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/99315037/66f07386-01dc-4c27-8f92-30d735453a82)

如图，PowerShell运行install安装时显示安装失败
我电脑本身装的python是3.11，重新下了3.10去适配这个脚本，然后PowerShell执行策略也改成了可运行脚本
具体应当怎么调整才能装上去？

**Comment by ZJChe** [comment]
环境变量配置好了吗？看报错好像是找不到python，如果打开一个cmd或者powershell，执行`python`或者`python3`显示找不到python，那就需要配置一下环境变量，请参考https://www.php.cn/faq/471645.html

**Comment by 0osmanthus** [comment]
从微软商店重装了python，检查了环境变量也没问题，现在venv创建好了但是安装到最后报错导致run.ps1无法运行
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/99315037/a336f03e-babe-4e8f-b683-da2fe022dd16)
如图所示
具体要怎么解决

**Comment by shiokaze** [comment]
检查python版本是否为3.10.9，如果不对的话，用readme里面提供的下载链接下载。

之前有人解决过类似问题，可以在closed的issue里面找一找

**Comment by ZJChe** [comment]
提示是缺少patch-ng模组，跑一下`pip install patch-ng`应该就行了
另外看起来使用微软商店安装python导致了一些意外的问题，正常通过官网安装python再运行install.ps1，是不会出现这个报错的（虽然也不一定会导致致命问题)。请确认一下`python --version`版本是不是为3.10.9

**Comment by 0osmanthus** [comment]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/99315037/262c8c79-caa5-4aa7-b4ed-e22299f9dcba)
如图，在控制台运行run.ps1后出现以上界面，是用户名路径为中文的原因吗？

**Comment by shiokaze** [comment]
是的，可以参考常见问题内的解决方案
