### ISSUE TITLE
install报错

### ISSUE THREAD

**Issue by less-fife** [shiokaze/UmamusumeAutoTrainer#89]
![LL{KD%1QY9@~BAJW CCF_~P](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/147199628/490c485a-f0ab-46c5-8606-a3262a827722)
环境变量也添加了，但是就是报错
![XNDPYG4UY46YU $N0FZ2AG1](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/147199628/3131835f-df09-445f-9461-35270c1b37ef)

**Comment by less-fife** [comment]
运行run闪退，用管理员也是报错
![JX(HKSXKOH9ZZ3%J 0EP46U](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/147199628/a68e4c3b-a256-4a6c-aae0-2f2b7b354aa0)

**Comment by shiokaze** [comment]
需要在脚本软件自身所在目录下执行

**Comment by less-fife** [comment]
哦，cd切换目录就行了
![G@ (2EUD6OTLC1Z3(G(~PA9](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/147199628/1274923f-d668-4ec8-8f16-714b6c1b2c46)
