### ISSUE TITLE
webui显示空白

### ISSUE THREAD

**Issue by HotBento** [shiokaze/UmamusumeAutoTrainer#9]
如图，powershell显示运行成功，但是网页一片空白。不知道什么原因。
python版本3.10.9，浏览器试过chrome和edge。

![bug](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/44371415/11fd150b-a072-472f-8b65-80e26ba624af)
![bug1](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/44371415/0fedfd0b-723c-48d4-a162-ce487f8306e9)
![bug2](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/44371415/ce905eb7-8497-4838-a340-3a69667328c1)

**Comment by shiokaze** [comment]
暂时没法复现，可能是浏览器版本或者电脑网络环境的问题

**Comment by HotBento** [comment]
参考解决方案：https://www.jianshu.com/p/6f139d8b64e3

**Comment by shiokaze** [comment]
ok，之后我在readme里记录一下
