### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by D-yyy** [shiokaze/UmamusumeAutoTrainer#92]
![捕获](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/63002838/7edf7df2-fe4b-4793-92a0-816bb184181b)
出现这个问题，请问该怎么解决

**Comment by YuanSnowing** [comment]
是不是python版本不对，python -V试一下呢

**Comment by D-yyy** [comment]
是3.9.7，是不是得升级一下

> 是不是python版本不对，python -V试一下呢

**Comment by YuanSnowing** [comment]
> 是3.9.7，是不是得升级一下
> 
> > 是不是python版本不对，python -V试一下呢

嗯嗯，升一下就好了，python3.10.9，[下载地址](https://www.python.org/downloads/release/python-3109/)
