### ISSUE TITLE
请问怎么更新？

### ISSUE THREAD

**Issue by CHI0454** [shiokaze/UmamusumeAutoTrainer#93]
我有在其他问题看到说用git pull的方式更新，但是完全不懂这方面的事，不管是在谷歌还是百度查关键词都没有看明白T T
有教程能偷懒最好，但是如果解释起来比较麻烦，可以告诉我具体应该查哪些关键词来学习嘛。。。

**Comment by YuanSnowing** [comment]
其实可以直接下载最新的代码，然后解压之后覆盖原来的就行qwq

如果你可以在代码所在的文件夹下打开终端，也可也执行 git pull --force，但是因为github需要vpn，所以有概率这样弄不下来。
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/53067358/60c6a9a3-8f6d-4f57-accd-4a72708e536e)
一般我就是摆烂地多试几次就好了qwq

想学习的话可以搜git使用教程啥的（git是一个代码管理的工具）emmmm不过日常用不到的话，我是不太推荐去学哈哈哈哈哈（在这个项目里大概git pull就够用了，或者其实直接下载+覆盖就够用了）。

**Comment by CHI0454** [comment]
我在文件夹用CMD输入的指令，反馈是下面的开头部分，然后百度之后说让输入GIT INIT，最后变成这样



X:\UmamusumeAutoTrainer-dev>git pull --force
fatal: not a git repository (or any of the parent directories): .git

X:\UmamusumeAutoTrainer-dev>git init
Initialized empty Git repository in X:/UmamusumeAutoTrainer-dev/.git/

X:\UmamusumeAutoTrainer-dev>git pull --force
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master


想了下还是不继续动了。。
直接覆盖可以的话我直接覆盖吧，感谢

**Comment by shiokaze** [comment]
简单来说，只有git clone 方式下载的代码才可以用git pull更新，如果你是用download zip下载的只能手动重新下载了

**Comment by CHI0454** [comment]
我还试了下git clone的方法，果然是VPN问题没法链接，想起来之前试AI作画用CMD链接GIT一直不成功的事了。。。

那我就固定期间覆盖更新吧，谢谢。
