### ISSUE TITLE
进入育成界面直接报错

### ISSUE THREAD

**Issue by Drayinese** [shiokaze/UmamusumeAutoTrainer#94]
进入育成界面直接报错状态5，没有任何行动
![Screenshot 2023-10-11 041159](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/80083242/e212707a-810b-4546-b027-44c3c1ccc08c)

**Comment by shiokaze** [comment]
依赖包的版本不对，可能是python版本不对导致的

**Comment by Drayinese** [comment]
把高版本的python卸载了以后重新安装了脚本可以正常启动了:D
