### ISSUE TITLE
识别问题

### ISSUE THREAD

**Issue by kano177** [shiokaze/UmamusumeAutoTrainer#98]
如图，这个识别是哪个设置出了问题
![)T%0@1M0937APIWB)~IPC5D](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/58425946/002946c0-d2ca-4376-bbe0-a00eadb7d41d)

**Comment by shiokaze** [comment]
必定出现吗？可能是模拟器分辨率或者画质的问题，目前我这没有遇到过

**Comment by shiokaze** [comment]
看了下，应该是那个回合体力太少了，跳过了分析训练数据的阶段直接休息，这样可以节省一些时间。

**Comment by kano177** [comment]
就是他有彩圈的时候会点没彩的地方，而且是毅力，我看了下分辨率是720*1080*180，应该是没问题吧，晚上我再试试
