### ISSUE TITLE
多开相关问题

### ISSUE THREAD

**Issue by Tilie** [shiokaze/UmamusumeAutoTrainer#99]
为了在本地多开，
我做了以下行为
1.复制整个项目一次
2.修改main.py中的监听端口为8072
3.修改adb端口为对应的模拟器
4.修改web\src\util\axiosConf.js中的第六行中的端口信息为8072

现在我遇到了个问题。复制后的项目的网页，点击“创建任务”没有反应。
能否给个找出原因的方向？

**Comment by shiokaze** [comment]
原因是你改了前端的源代码但是没有构建，需要在web文件夹内执行npm run build之后把dist内的文件复制到public内才能正常使用，如果没有npm命令的话需要安装node.js

**Comment by Tilie** [comment]
谢谢你的及时回复，我尝试了你说的做法，一开始并不起效.
在某次我先启动了python程序2，再启动了原先的python程序1，意外的发现了程序2的按钮可以点击了，但是程序1的按钮随之失灵.
我怀疑有其他资源上的占用问题，请问你有什么思路吗？

**Comment by shiokaze** [comment]
可以在浏览器内用f12查看按下创建任务按钮后网络请求的报错情况
暂时没有试过多开的情况，但是理论上不会有占用问题

**Comment by Tilie** [comment]
问题有个不优雅的解决方式，即直接使用两个浏览器.

我发现任意一个浏览器只要打开了其中一个就打不开另外一个，但此时使用另外一个浏览器能打开前面说的后者。

谢谢你的帮忙。

**Comment by shiokaze** [comment]
ok
